### ISSUE TITLE
New GurbaniNow API Response Layout

### ISSUE THREAD

**Issue by sarabveer** [bogas04/SikhJS#102]
The JSON Response has been cleaned up

https://api.gurbaninow.com/v2/search/hhnApp/

https://api.gurbaninow.com/v2/shabad/1

**Comment by bogas04** [comment]
Thanks a lot for the heads up, will fix it up soon. You should have versioned the API so that existing apps don't break however.

**Comment by Sarabveer** [comment]
Not that many apps use my API yet, will implement versioning soon.

**Comment by sarabveer** [comment]
Should I move the api to `api.gurbaninow.com/v2`?

**Comment by sarabveer** [comment]
@bogas04 API has moved to /v2/ to ease versioning in the future.
