### ISSUE TITLE
Use GurbaniNow for Hukamnama

### ISSUE THREAD

**Issue by sarabveer** [bogas04/SikhJS#103]
GurbaniNow has more advanced Hukamnama ouput.

https://github.com/GurbaniNow/gurbaninow-api#get-todays-hukamnama-from-darbar-sahib-amritsar

It also supports archives.

**Comment by bogas04** [comment]
Thanks, but I still love the robustness of SGPC website.

**Comment by sarabveer** [comment]
It uses SGPC
