### ISSUE TITLE
Japuji Sahib doesn't display 'II'

### ISSUE THREAD

**Issue by plug-n-play** [bogas04/SikhJS#106]
Japuji Sahib doesn't displays 'II' marking end of line.

For e.g., following gets displayed,

![image](https://user-images.githubusercontent.com/6245927/26852468-051beb20-4b2c-11e7-844a-c11af097b19c.png)

instead of,

![image](https://user-images.githubusercontent.com/6245927/26852531-330ba4e4-4b2c-11e7-849f-73a7af5ce72a.png)

On installing the Dev-environment locally, along with Gurmukhi fonts, the issue is not reproduced while viewing the markdown conversion in code-editor.

It turns out that the process which converts .md to html removes the character ']' altogether

**Comment by bogas04** [comment]
Thanks a lot of raising it, it's actually a known bug. The [problem](https://github.com/developit/snarkdown/issues/12) is with new dependency for markdown (snarkdown). For now one quick way to fix it would be to use || over ]], but we might lose out on better glyphs.

If it makes sense to you, we can probably replace all ]] and ] with || and | in a new PR.

**Comment by bogas04** [comment]
@plug-n-play Jee. Finally I got free from hectic project at work. I think we can move to some other markdown dependency for now.

**Comment by bogas04** [comment]
Switching to remarkable gives us a big hit in bundle size, but we can recover it later.

| snarkdown | remarkable | markdown | updated deps with markdown |
|:--:|:--:|:--:|:--:|
|main.js  87.1 kB <br /> vendor.js   340 kB | main.js  87.1 kB  <br/> vendor.js   427 kB | main.js 87.2 kB <br/> vendor.js 362 kB | main.js  87.2 kB <br /> vendor.js  322 kB  |

**Comment by bogas04** [comment]
Fixed by 39b944807d21f11ed8fa41dcf13eaa5fca42d84e
