### ISSUE TITLE
Improve UI of Calendar

### ISSUE THREAD

**Issue by ravjot28** [bogas04/SikhJS#15]
Related to #52

**Comment by ravjot28** [comment]
Found one iOS app doing similar to what I was visualizing 

MySikhi - Nitnem & Calendar by MySIkhi
https://appsto.re/ca/OzTRH.i

**Comment by bogas04** [comment]
This component [LGTM](http://intljusticemission.github.io/react-big-calendar/examples/index.html)

**Comment by bogas04** [comment]
The dependency has added extra 400 kb to our bundle and requires external CSS. I think we'll have to create our custom Calendar component to be super lightweight.
