### ISSUE TITLE
Sri guru granth sahib tab previous set next set and drop down are not in sync when switched to night mode

### ISSUE THREAD

**Issue by ravjot28** [bogas04/SikhJS#17]

**Comment by bogas04** [comment]
Related to https://github.com/bogas04/SikhJS/issues/8

**Comment by bogas04** [comment]
irrelevant after 4e34ace843e03f412c921247c31e52e3d5002710

NOTE: Master is not maintained anymore and the changes are being done to gh-pages

https://bogas04.github/SikhJS
