### ISSUE TITLE
Add Bookmark feature in Guru Granth Sahib tab

### ISSUE THREAD

**Issue by ravjot28** [bogas04/SikhJS#20]

**Comment by bogas04** [comment]
Regarding point 2, a very neat thing can be made.

A link can be made which would encapsulate all your data in query params from localStorage and when opened on mobile, it would replace localStorage with the same. QR Code of such link can be generated to give the feel as if some syncing is happening. 

Summarizing:
- User clicks `Generate Export Link`
- A link is generated which when pasted on some other browser would open up SikhJS, and a special route would then take up all the params to refill localStorage
- A QR code of above link can be created too for users with mobile. It can simply have URL to above link or the data stringified, which the QR reader (can be part of SikhJS) can read and parse.

**Comment by bogas04** [comment]
We can simply have favorites sections which would have links, date and title

sggs/:ang
shabads/:q
shabad/:I'd

All can be easily saved, giving a very nice feature for free.

**Comment by bogas04** [comment]
[localForage](https://github.com/localForage/localForage) looks like a good library to use (with IndexDB) for this.

``` javascript
bookmarks: [{
  id: 1234,
  timestamp: 1477289286572,
  title: 'Ghat Ghat Mai Harjuu Basae',
  link: `http://bogas04.github.io/SikhJS/#/shabad/5491`,
  data: {
    // can other meta data added by user like katha links, kirtan links
  }
}]
```

**Comment by bogas04** [comment]
We still need to sync between mobile and desktop somehow, I don't really want to create a server for the project, maybe we can use [FireBase](https://firebase.google.com/) with Facebook/Twitter OAuth

Also I really need some more devs, I'm tired of making this seem like I'm talking to someone else :sob:

**Comment by bogas04** [comment]
I'm working with [Dexie](http://dexie.org/) for now. 

Ditching localForage idea as it is essentially localStorage async API using IDB/WebSQL/LocalStorage. Our use case isn't key value storage to be honest.

For benchmarks on all these libraries, you can see [this video](https://www.youtube.com/watch?v=4FBTPSWSXuU). It explains what the situation is with DOM and I/O perf.
