### ISSUE TITLE
Please notify user that Hukamnama will be downloaded as pdf

### ISSUE THREAD

**Issue by davchana** [bogas04/SikhJS#29]
I came to know about this app from reddit.

Action:
When user clicks the menu item Hukamnama on left hand side,

Expectations:
The app will display the Hukamnama Text here, in app itself, its its won web-view.

What happens:
Chrome/Phone starts downloading a pdf, and notifies: PDF downloaded - Hukamnama.pdf.

Issue:
User needs to open a separate app to view this pdf.
The next time user clicks, the pdf gets saved as Hukamnama(01).pdf

Suggestions:
I understand that it might be cause there is no Hukamnama text API available, only a pdf link is available from SGPC website (?). I might be wrong, please see if a text API is available?

**Comment by bogas04** [comment]
Thank you so much for raising this issue.

Yes, currently the app just relies on browser taking the action on the PDF, in case you have the PDF viewer enabled in your browser, it'll open as a PDF inside the web page, or it'll ask you to download it. 

Yes, there's no text API available as such, I'm planning to [extract](http://stackoverflow.com/questions/1554280/extract-text-from-pdf-in-javascript) the hukamnama from the PDF and thereby create a text API reliant on SGPC website.

**Comment by davchana** [comment]
Ok, thanks, could you tag this as feature?, as not-urgent.
