### ISSUE TITLE
Change bookmark icon

### ISSUE THREAD

**Issue by ravjot28** [bogas04/SikhJS#63]
Right now it is difficult to understand the bookmark icon and I think any elder looking at the icon will not have any clue for the same. So change it or find any alternative

**Comment by bogas04** [comment]
#52 will fix this

![screen shot 2016-11-01 at 7 11 08 am](https://cloud.githubusercontent.com/assets/6177621/19873459/69879dfa-a002-11e6-971a-81964e6bcc58.png)
![screen shot 2016-11-01 at 7 11 12 am](https://cloud.githubusercontent.com/assets/6177621/19873460/698cf732-a002-11e6-9e01-a7cdc21482c9.png)
