### ISSUE TITLE
Nightly mode looks bit weird for header as the color is pink

### ISSUE THREAD

**Issue by ravjot28** [bogas04/SikhJS#66]
I think more focus should be in  the content like shabad, or search results etc. So better we keep everything black and avoid pink

**Comment by bogas04** [comment]
Yeah it's a problem with material-ui dependency. #52 will fix this.

![screen shot 2016-11-01 at 7 07 09 am](https://cloud.githubusercontent.com/assets/6177621/19873364/f74b31c0-a001-11e6-90cb-1f14faa7e26a.png)
![screen shot 2016-11-01 at 7 07 51 am](https://cloud.githubusercontent.com/assets/6177621/19873365/f74ee4f0-a001-11e6-907c-96eed3f1f281.png)
