### ISSUE TITLE
Safari fews things are not working, try to bring cross platform compatibility

### ISSUE THREAD

**Issue by ravjot28** [bogas04/SikhJS#67]
Safari fews things are not working, try to bring cross platform compatibility

**Comment by bogas04** [comment]
Can you please list the errors ?

So far latest versions of Firefox and Chrome are supported.

Safari 10 as of 1st November doesn't support:
- [x] [fetch](http://caniuse.com/#search=fetch). Need to add [polyfill](https://gist.github.com/Couto/b29676dd1ab8714a818f) for Safari.

**Comment by bogas04** [comment]
We will be targeting better support for all browsers only during 1.0.0 release. Until then to ensure fast development, we'll simply use latest standards.

**Comment by bogas04** [comment]
Add unfetch polyfill. Should be working now, as of 29c19155048db4990ef7b0439b2c4250662f64e8
