### ISSUE TITLE
Reduce Bundle Size

### ISSUE THREAD

**Issue by bogas04** [bogas04/SikhJS#95]
Big Wins:
* [ ] Replace BigCalendar with custom Calendar. (~41.4%)
* [ ] Use preact. (~21%)
* [ ] Get rid of react-mdl*? (~6.2 + loss of extraneous assets) 
* [ ] ...

Small Wins:
* [ ] Use webpack 2 tree shaking, code splitting etc #84 .
  * [ ] Use more webpack uglification/optimization plugins.
* [ ] Use better babel presets. Modern app can target modern browsers I guess?
* [ ] Move [nitnem constants](https://github.com/bogas04/SikhJS/blob/master/js/components/Nitnem/constants.js) to docs/json/ and get them by network requests. (~0.5).
* [ ] ...

* *Note: I am seriously reconsidering the use of any UI kit. One kit doesn't fit all IMO. I think [styled-componets](https://github.com/styled-components/styled-components) would be good enough.

Module | Used By | Size (%)
:--|:--|:--
React | App | 21
Lodash | Calendar | 18
Moment | Calendar | 16
react-big-calendar | Calendar | 7.4
dexie | App | 6.7
react-mdl | App | 6.2
remarkable | App | 6.2
react-router | App | 3
autolinker | ??? | 2.8
history | react-router | 1.6
lodash.isequal | react-mdl | 1.5
react-overlays | ??? | 1.2
fbjs | react stuff | 1.1
Nitnem | App | 0.79
react-throttle | App | 0.61
dom-helpers | ??? | 0.52
...

**Comment by jdalton** [comment]
You may dig [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin).

**Comment by bogas04** [comment]
Thank you so much @jdalton

**Comment by bogas04** [comment]
Useful [talk](https://www.youtube.com/watch?v=e8XejNt5SZo) from CDS2016

**Comment by bogas04** [comment]
#104 Is dealing with it in `rewrite` branch.
